[package]
name = "gin_codegen"
version = "0.1.0"
authors = ["Cameron Wheeler <cwheel@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.23"
quote = "1.0.6"
proc-macro2 = "1.0.15"
juniper = "0.14.2"