name: CI

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '14'
     - run: npm install
     - run: npx vuepress build docs
     - run: npx gh-pages -d docs/.vuepress/dist --user "Github Actions <noreply@github.com>" --repo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$INPUT_REPO.git"
